In [43]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.ticker as mtick  
import matplotlib.pyplot as plt
%matplotlib inline

In [44]:
df= pd.read_csv("tel_churn.csv")

In [45]:
df.head()

Unnamed: 0  customerID  gender SeniorCitizen Partner Dependents  tenure  \
0           0  7590-VHVEG  Female            No     Yes         No       1   
1           1  5575-GNVDE    Male            No      No         No      34   
2           2  3668-QPYBK    Male            No      No         No       2   
3           3  7795-CFOCW    Male            No      No         No      45   
4           4  9237-HQITU  Female            No      No         No       2   

  PhoneService     MultipleLines InternetService  ... TechSupport StreamingTV  \
0           No  No phone service             DSL  ...          No          No   
1          Yes                No             DSL  ...          No          No   
2          Yes                No             DSL  ...          No          No   
3           No  No phone service             DSL  ...         Yes          No   
4          Yes                No     Fiber optic  ...          No          No   

  StreamingMovies        Contract PaperlessBilling              PaymentMethod  \
0              No  Month-to-month              Yes           Electronic check   
1              No        One year               No               Mailed check   
2              No  Month-to-month              Yes               Mailed check   
3              No        One year               No  Bank transfer (automatic)   
4              No  Month-to-month              Yes           Electronic check   

  MonthlyCharges TotalCharges Churn  tenure_group  
0          29.85        29.85     0        Year 1  
1          56.95      1889.50     0        Year 3  
2          53.85       108.15     1        Year 1  
3          42.30      1840.75     0        Year 4  
4          70.70       151.65     1        Year 1  

[5 rows x 23 columns]

In [46]:
df.drop(columns=['Unnamed: 0','customerID'],axis=1,inplace=True)

In [47]:
df.head()

gender SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female            No     Yes         No       1           No   
1    Male            No      No         No      34          Yes   
2    Male            No      No         No       2          Yes   
3    Male            No      No         No      45           No   
4  Female            No      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  ...  \
0  No phone service             DSL             No          Yes  ...   
1                No             DSL            Yes           No  ...   
2                No             DSL            Yes          Yes  ...   
3  No phone service             DSL            Yes           No  ...   
4                No     Fiber optic             No           No  ...   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  tenure_group  
0           Electronic check          29.85         29.85      0        Year 1  
1               Mailed check          56.95       1889.50      0        Year 3  
2               Mailed check          53.85        108.15      1        Year 1  
3  Bank transfer (automatic)          42.30       1840.75      0        Year 4  
4           Electronic check          70.70        151.65      1        Year 1  

[5 rows x 21 columns]

In [48]:
df=pd.get_dummies(df)

In [49]:
df.head()

tenure  MonthlyCharges  TotalCharges  Churn  gender_Female  gender_Male  \
0       1           29.85         29.85      0              1            0   
1      34           56.95       1889.50      0              0            1   
2       2           53.85        108.15      1              0            1   
3      45           42.30       1840.75      0              0            1   
4       2           70.70        151.65      1              1            0   

   SeniorCitizen_No  SeniorCitizen_Yes  Partner_No  Partner_Yes  ...  \
0                 1                  0           0            1  ...   
1                 1                  0           1            0  ...   
2                 1                  0           1            0  ...   
3                 1                  0           1            0  ...   
4                 1                  0           1            0  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  tenure_group_Year 1  tenure_group_Year 2  \
0                           0                    1                    0   
1                           1                    0                    0   
2                           1                    1                    0   
3                           0                    0                    0   
4                           0                    1                    0   

   tenure_group_Year 3  tenure_group_Year 4  tenure_group_Year 5  \
0                    0                    0                    0   
1                    1                    0                    0   
2                    0                    0                    0   
3                    0                    1                    0   
4                    0                    0                    0   

   tenure_group_Year 6  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  

[5 rows x 53 columns]

In [50]:
df.columns

Index(['tenure', 'MonthlyCharges', 'TotalCharges', 'Churn', 'gender_Female',
       'gender_Male', 'SeniorCitizen_No', 'SeniorCitizen_Yes', 'Partner_No',
       'Partner_Yes', 'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One yea

In [54]:
#Seperating Features culumn from Target column:
X=df.drop(columns = 'Churn',axis=1)
Y=df['Churn']

In [55]:
X

tenure  MonthlyCharges  TotalCharges  gender_Female  gender_Male  \
0          1           29.85         29.85              1            0   
1         34           56.95       1889.50              0            1   
2          2           53.85        108.15              0            1   
3         45           42.30       1840.75              0            1   
4          2           70.70        151.65              1            0   
...      ...             ...           ...            ...          ...   
7027      24           84.80       1990.50              0            1   
7028      72          103.20       7362.90              1            0   
7029      11           29.60        346.45              1            0   
7030       4           74.40        306.60              0            1   
7031      66          105.65       6844.50              0            1   

      SeniorCitizen_No  SeniorCitizen_Yes  Partner_No  Partner_Yes  \
0                    1                  0           0            1   
1                    1                  0           1            0   
2                    1                  0           1            0   
3                    1                  0           1            0   
4                    1                  0           1            0   
...                ...                ...         ...          ...   
7027                 1                  0           0            1   
7028                 1                  0           0            1   
7029                 1                  0           0            1   
7030                 0                  1           0            1   
7031                 1                  0           1            0   

      Dependents_No  ...  PaymentMethod_Bank transfer (automatic)  \
0                 1  ...                                        0   
1                 1  ...                                        0   
2                 1  ...                                        0   
3                 1  ...                                        1   
4                 1  ...                                        0   
...             ...  ...                                      ...   
7027              0  ...                                        0   
7028              0  ...                                        0   
7029              0  ...                                        0   
7030              1  ...                                        0   
7031              1  ...                                        1   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                         0                               1   
1                                         0                               0   
2                                         0                               0   
3                                         0                               0   
4                                         0                               1   
...                                     ...                             ...   
7027                                      0                               0   
7028                                      1                               0   
7029                                      0                               1   
7030                                      0                               0   
7031                                      0                               0   

      PaymentMethod_Mailed check  tenure_group_Year 1  tenure_group_Year 2  \
0                              0                    1                    0   
1                              1                    0                    0   
2                              1                    1                    0   
3                              0                    0                    0   
4                              0                    1                    0   
...                          .

In [56]:
Y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

**Importing skelarn**

In [80]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [81]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3)

## Decision Tree Classifier

In [82]:
model=DecisionTreeClassifier(criterion='gini',max_depth=6, min_samples_leaf=8, random_state=100)

In [83]:
model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [84]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [85]:
confusion_matrix(y_test,y_pred)

array([[1381,  178],
       [ 269,  282]], dtype=int64)

In [86]:
print(classification_report(y_test,y_pred,labels=[1,0]))

              precision    recall  f1-score   support

           1       0.61      0.51      0.56       551
           0       0.84      0.89      0.86      1559

    accuracy                           0.79      2110
   macro avg       0.73      0.70      0.71      2110
weighted avg       0.78      0.79      0.78      2110



**OBSERVATIONS**
* Although the accuracy is good (~80%), its not giving full picture. (Accuracy is cursed)
* For minority class i.e. for churners, precision, recall, f1-score are very low : hence this model is not up to the mark.
* This is because, the dataset is highly imbalanced.

## Over-sampling using SMOTE and cleaning using ENN.

In [90]:
sm = SMOTEENN()
X_resampled, Y_resampled = sm.fit_resample(X,Y)

In [91]:
xr_train, xr_test, yr_train, yr_test = train_test_split(X_resampled,Y_resampled, test_size=0.3)

## Decision Tree Classifier after Over-sampling

In [111]:
model_dt=DecisionTreeClassifier(criterion='gini',max_depth=6, min_samples_leaf=8, random_state=100)

In [112]:
model_dt.fit(xr_train, yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [119]:
yr_pred_dt=model_dt.predict(xr_test)
yr_pred_dt

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [114]:
confusion_matrix(yr_test,yr_pred_dt)

array([[718,  48],
       [ 58, 940]], dtype=int64)

In [120]:
print(classification_report(yr_test,yr_pred_dt,labels=[1,0]))

              precision    recall  f1-score   support

           1       0.95      0.94      0.95       998
           0       0.93      0.94      0.93       766

    accuracy                           0.94      1764
   macro avg       0.94      0.94      0.94      1764
weighted avg       0.94      0.94      0.94      1764



Since the dataset is balanced hence Accuracy is considerable.

## Random Forest Classifier

In [121]:
from sklearn.ensemble import RandomForestClassifier

In [122]:
model_rf=RandomForestClassifier(n_estimators=150,criterion='gini',max_depth=6, min_samples_leaf=8, random_state=100)

In [123]:
model_rf.fit(xr_train, yr_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, n_estimators=150,
                       random_state=100)

In [124]:
yr_pred_rf=model.predict(xr_test)
yr_pred_rf

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [127]:
model_rf_score = model_rf.score(xr_test, yr_test)
print(model_rf_score)

0.9552154195011338


In [128]:
confusion_matrix(yr_test,yr_pred_rf)

array([[716,  50],
       [ 29, 969]], dtype=int64)

In [129]:
print(classification_report(yr_test,yr_pred_rf,labels=[1,0]))

              precision    recall  f1-score   support

           1       0.95      0.97      0.96       998
           0       0.96      0.93      0.95       766

    accuracy                           0.96      1764
   macro avg       0.96      0.95      0.95      1764
weighted avg       0.96      0.96      0.96      1764



## Logistics Regression

In [132]:
from sklearn import linear_model

In [138]:
model_lr = linear_model.LogisticRegression(max_iter= 1000)
model_lr.fit(xr_train,yr_train)
yr_pred_lr = model_lr.predict(xr_test)
model_lr_score = model_lr.score(xr_test, yr_test)
print("Model Score : " ,model_lr_score, "\n")
print(metrics.classification_report(yr_test, yr_pred_lr))

Model Score :  0.9574829931972789 

              precision    recall  f1-score   support

           0       0.95      0.96      0.95       766
           1       0.97      0.96      0.96       998

    accuracy                           0.96      1764
   macro avg       0.96      0.96      0.96      1764
weighted avg       0.96      0.96      0.96      1764



C:\Users\Aniket Tiwari\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## SupportVectorClassifier

In [ ]:
from sklearn.svm import SVC  

In [ ]:
model_svc = SVC(kernel='linear') 
model_svc.fit(xr_train,yr_train)
yr_pred_svc = model_svc.predict(xr_test)
model_svc_score = model_svc.score(xr_test, yr_test)
print("Model Score : " ,model_svc_score, "\n")
print(metrics.classification_report(yr_test, yr_pred_svc))